#!/usr/bin/env python3
"""
gen_font.py - Generate C bitmap font headers for X4Display.

Usage:
    python3 tools/gen_font.py <ttf_path> <pixel_size> <output_header> <SYMBOL_NAME>

The output header defines:
  - SYMBOL_NAME_DATA[numChars][bytesPerGlyph]  (static const uint8_t array)
  - SYMBOL_NAME_INSTANCE                        (static const BitmapFont)

FontData.cpp then copies each _INSTANCE into the extern-linkage BitmapFont
variable declared in BitmapFont.h.

Format: row-major, 1 bpp, MSB = leftmost pixel of each row.
  bytesPerRow = ceil(glyphW / 8)
  bytesPerGlyph = glyphH * bytesPerRow
"""
import sys, math, os, freetype


def generate_font_header(ttf_path, pixel_size, out_path, symbol_name,
                         extra_line_leading=4):
    face = freetype.Face(ttf_path)
    face.set_pixel_sizes(0, pixel_size)

    asc  = face.size.ascender >> 6
    desc = abs(face.size.descender >> 6)
    glyph_h = asc + desc

    face.load_char('M', freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
    advance  = face.glyph.advance.x >> 6
    glyph_w  = advance

    bytes_per_row   = math.ceil(glyph_w / 8)
    bytes_per_glyph = glyph_h * bytes_per_row
    line_h = glyph_h + extra_line_leading

    FIRST_CHAR = 0x20
    LAST_CHAR  = 0x7E
    num_chars  = LAST_CHAR - FIRST_CHAR + 1

    all_glyph_data = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        canvas = [[0] * glyph_w for _ in range(glyph_h)]
        face.load_char(code, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        bm        = face.glyph.bitmap
        bear_left = face.glyph.bitmap_left
        bear_top  = face.glyph.bitmap_top
        x_off = bear_left
        y_off = asc - bear_top
        for row in range(bm.rows):
            cy = y_off + row
            if cy < 0 or cy >= glyph_h:
                continue
            for col in range(bm.width):
                cx = x_off + col
                if cx < 0 or cx >= glyph_w:
                    continue
                byte_idx = col >> 3
                bit_idx  = 7 - (col & 7)
                pixel_on = (bm.buffer[row * bm.pitch + byte_idx] >> bit_idx) & 1
                if pixel_on:
                    canvas[cy][cx] = 1
        glyph_bytes = []
        for row in canvas:
            for b in range(bytes_per_row):
                byte = 0
                for bit in range(8):
                    col = b * 8 + bit
                    if col < glyph_w and row[col]:
                        byte |= (0x80 >> bit)
                glyph_bytes.append(byte)
        all_glyph_data.append((chr(code), glyph_bytes))

    varname_data = symbol_name + "_DATA"
    L = []
    L.append("#pragma once")
    L.append("// " + chr(0x2500)*77)
    L.append("// " + os.path.basename(out_path) +
             " -- Fira Code bitmap font (%dx%d px)" % (glyph_w, glyph_h))
    L.append("//")
    L.append("// Generated by tools/gen_font.py from FiraCode-Regular.ttf at %dpx." % pixel_size)
    L.append("// Format: row-major, 1 bpp, MSB=left pixel.")
    L.append("// Each glyph: %d rows x %d byte(s)/row = %d bytes." %
             (glyph_h, bytes_per_row, bytes_per_glyph))
    L.append("// Covers ASCII 0x20-0x7E (%d glyphs)." % num_chars)
    L.append("//")
    L.append("// IMPORTANT: include from exactly ONE .cpp file (FontData.cpp).")
    L.append("// " + chr(0x2500)*77)
    L.append("")
    L.append('#include "BitmapFont.h"')
    L.append("")
    L.append("// clang-format off")
    L.append("static const uint8_t %s[%d][%d] = {" % (varname_data, num_chars, bytes_per_glyph))
    for (ch, glyph_bytes) in all_glyph_data:
        hex_vals = ",".join("0x%02X" % b for b in glyph_bytes)
        esc = repr(ch)[1:-1]
        L.append("    {%s}, // 0x%02X '%s'" % (hex_vals, ord(ch), esc))
    L.append("};")
    L.append("// clang-format on")
    L.append("")
    L.append("static const BitmapFont %s_INSTANCE = {" % symbol_name)
    L.append("    /* data        */ &%s[0][0]," % varname_data)
    L.append("    /* bytesPerRow */ %d," % bytes_per_row)
    L.append("    /* glyphW      */ %d," % glyph_w)
    L.append("    /* glyphH      */ %d," % glyph_h)
    L.append("    /* advance     */ %d," % advance)
    L.append("    /* lineH       */ %d," % line_h)
    L.append("    /* firstChar   */ 0x%02X," % FIRST_CHAR)
    L.append("    /* numChars    */ %d," % num_chars)
    L.append("    /* columnMajor */ false,")
    L.append("};")
    L.append("")

    with open(out_path, 'w') as f:
        f.write('\n'.join(L))

    print("Generated %s: %dx%d glyph, advance=%d, lineH=%d, "
          "%d bytes/glyph, total data=%d bytes" %
          (out_path, glyph_w, glyph_h, advance, line_h,
           bytes_per_glyph, num_chars * bytes_per_glyph))


if __name__ == "__main__":
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)
    ttf_path, pixel_size_s, out_path, symbol_name = sys.argv[1:]
    generate_font_header(ttf_path, int(pixel_size_s), out_path, symbol_name)
